language: python
python:
  - "3.9"

install:
  - pip install -r requirements.txt

before_script:
  - curl -LO https://www.sqlite.org/2022/sqlite-tools-win32-x86-3360000.zip
  - 7z x sqlite-tools-win32-x86-3360000.zip -osqlite
  - export PATH=$PATH:$PWD/sqlite

  - python manage.py makemigrations carservice
  - python manage.py makemigrations users
  - python manage.py migrate carservice
  - python manage.py migrate users
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py runserver
  - python manage.py test

notifications:
  email:
    recipients:
      - projectofwiners@gmail.com
    on_success: always
    on_failure: always
