language: python
python:
  - "3.9"

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py makemigrations carservice
  - python manage.py makemigrations users
  - python manage.py migrate carservice
  - python manage.py migrate users

script:
  - python manage.py test

services:
  - sqlite3
