# Generated by Django 4.0.6 on 2023-06-24 10:19

import carservice.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=17, validators=[carservice.models.validate_ser_num])),
                ('car_mileage', models.PositiveIntegerField()),
                ('car_model', models.CharField(max_length=30)),
                ('car_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(10.0)])),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carservice.car')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('active', 'Rent active'), ('finished', 'Rent finished')], max_length=30, null=True)),
                ('rent_start', models.DateField(null=True)),
                ('rent_stop', models.DateField(null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carservice.offer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
