# Generated by Django 4.0.6 on 2023-06-18 18:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=17)),
                ('car_mileage', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(300000)])),
                ('car_model', models.CharField(max_length=30)),
                ('car_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.FloatField(validators=[django.core.validators.MaxValueValidator(10.0)])),
                ('id_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carservice.car')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('rent_duration', models.DurationField()),
                ('id_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carservice.offer')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carservice.user')),
            ],
        ),
    ]
