# Generated by Django 4.0.6 on 2023-06-24 11:54

import carservice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_year',
        ),
        migrations.AddField(
            model_name='car',
            name='year_of_prod',
            field=models.DateField(null=True, validators=[carservice.models.validate_year]),
        ),
    ]
