# Generated by Django 4.0.6 on 2023-06-18 20:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carservice', '0002_alter_offer_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='id_car',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='id_offer',
            new_name='offer',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='rent_duration',
        ),
        migrations.AddField(
            model_name='rent',
            name='rent_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='rent_stop',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_mileage',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(10.0)]),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
