# Generated by Django 4.0.6 on 2023-06-21 20:15

import carservice.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carservice', '0003_rename_id_car_offer_car_rename_id_offer_rent_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='serial_number',
            field=models.CharField(max_length=17, validators=[carservice.models.validate_ser_num]),
        ),
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
