# Generated by Django 4.0.6 on 2023-06-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0003_rename_id_car_offer_car_rename_id_offer_rent_offer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='status',
        ),
    ]
