# Generated by Django 4.0.6 on 2023-06-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0004_remove_rent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='status_field',
            field=models.CharField(default='inactive', max_length=8),
        ),
    ]
