# Generated by Django 4.0.6 on 2023-06-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0004_alter_car_serial_number_alter_rent_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Rent active'), ('finished', 'Rent finished')], max_length=30, null=True),
        ),
    ]
