# Generated by Django 4.0.6 on 2023-06-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0005_rent_status_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='status_field',
        ),
        migrations.AddField(
            model_name='rent',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
