# Generated by Django 4.0.6 on 2023-06-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0005_offer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_brand',
            field=models.CharField(choices=[('Volkswagen', 'Volkswagen'), ('BMW', 'BMW'), ('Audi', 'Audi'), ('Ford', 'Ford'), ('Opel', 'Opel'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Renault', 'Renault'), ('Skoda', 'Skoda'), ('Toyota', 'Toyota'), ('Peugeot', 'Peugeot'), ('Hyundai', 'Hyundai'), ('Citroën', 'Citroën'), ('Volvo', 'Volvo'), ('Nissan', 'Nissan'), ('Fiat', 'Fiat'), ('Seat', 'Seat'), ('Mazda', 'Mazda'), ('Honda', 'Honda'), ('Suzuki', 'Suzuki'), ('Jeep', 'Jeep'), ('Dacia', 'Dacia'), ('Mitsubishi', 'Mitsubishi'), ('MINI', 'MINI'), ('Other', 'Other')], default='1', max_length=30),
        ),
    ]
