# Generated by Django 4.0.6 on 2023-06-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0008_alter_rent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(editable=False, max_length=30),
        ),
    ]
