# Generated by Django 4.0.6 on 2023-06-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0009_alter_rent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(default='inactive', max_length=30),
        ),
    ]
