# Generated by Django 4.0.6 on 2023-06-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0010_alter_rent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
